import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BottomNav from "@/presentation/layout/BottomNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white relative min-h-screen overflow-x-clip`}
      >
        {/* Decorative gradient circles background */}
       {/*  <div aria-hidden className='pointer-events-none fixed inset-0 -z-10 overflow-hidden'>
      
          <div
            className='absolute left-[55%] top-[40%] -translate-x-1/2 -translate-y-1/2 h-[34rem] w-[34rem] rounded-full bg-gradient-to-br from-fuchsia-500 via-purple-600 to-sky-500 opacity-20 blur-[140px]'
          />
          
          <div
            className='absolute left-[30%] top-[75%] -translate-x-1/2 -translate-y-1/2 h-[26rem] w-[26rem] rounded-full bg-gradient-to-br from-rose-500 to-orange-400 opacity-14 blur-[120px]'
          />
          
          <div className='absolute -top-32 -left-24 h-[28rem] w-[28rem] rounded-full bg-gradient-to-br from-sky-400 to-cyan-500 opacity-14 blur-[120px]' />
          <div className='absolute -bottom-32 -right-24 h-[28rem] w-[28rem] rounded-full bg-gradient-to-br from-amber-400 to-rose-500 opacity-12 blur-[120px]' />
         
          <div className='absolute left-[-10%] top-1/2 -translate-y-1/2 h-[90%] w-[18rem] rounded-full bg-gradient-to-b from-emerald-400/0 via-emerald-400/20 to-teal-500/0 blur-[120px]' />
          
          <div
            className='absolute top-10 left-[15%] h-60 w-60 rounded-full bg-gradient-to-br from-cyan-400 to-blue-500 opacity-15 blur-[100px]'
          />
          <div
            className='absolute top-[55%] left-6 h-64 w-64 rounded-full bg-gradient-to-br from-emerald-400 to-teal-500 opacity-12 blur-[110px]'
          />
          <div
            className='absolute top-[18%] right-8 h-56 w-56 rounded-full bg-gradient-to-br from-violet-500 to-fuchsia-500 opacity-14 blur-[110px]'
          />
          <div
            className='absolute bottom-6 left-[10%] h-52 w-52 rounded-full bg-gradient-to-br from-amber-400 to-rose-400 opacity-12 blur-[100px]'
          />
          <div
            className='absolute bottom-10 right-[12%] h-64 w-64 rounded-full bg-gradient-to-br from-sky-400 to-indigo-500 opacity-12 blur-[110px]'
          />
        </div> */}

        <div className='container  mx-auto max-w-2xl py-28 md:py-32 px-6 relative z-10'>
          {children}
        </div>
        <div className='relative z-10'>
          <BottomNav />
        </div>
      </body>
    </html>
  );
}
